language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
cache: cargo
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libdbus-1-3
    - libdbus-1-dev

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
